import express from "express";
import {getAllUser, superAdminLogin, superAdminLogout, superAdminRegistration,forgotPassword, resetPassword } from "../../Controller/SuperAdminController/superAdminController.js";
import { superAdminMiddleware } from "../../Middleware/AuthMiddleware.js";
const superadminRouter = express.Router();
superadminRouter.post("/auth/signup", superAdminRegistration);
superadminRouter.post("/auth/signin", superAdminLogin);
superadminRouter.get("/auth/logout", superAdminMiddleware, superAdminLogout);
superadminRouter.get("/get-all-users",superAdminMiddleware, getAllUser);
superadminRouter.post("/forgot-password", forgotPassword);
superadminRouter.post("/reset-password/:id/:token", resetPassword);
export default superadminRouter;
